### PR TITLE
fixes intermittent multiple job invocations

### LINKED ISSUE #32: This plugin triggers the build twice
### Version report

Jenkins and plugins versions report:

```
Plugin version - 2.3
Jenkins version - 2.235.1
--


<br class="Apple-interchange-newline">
```

- What Operating System are you using (both controller, and any agents involved in the problem)?

```
Paste here
```

### Reproduction steps

- Step 1 - Enable pull request review webhook in github (as mentioned below)
image

- Step 2 - Configure build on pull request review - as shown below
image

### Results

Expected result:

it should trigger a build only once when the pr is approved.

Actual result:

its triggering the build twice everytime when the pr is approved.

### PR DESCRIPTION
**Pull request by lprimak**
Fixes #32

- [X ] Ensure that the pull request title represents the desired changelog entry
- [X ] Please describe what you did
- [ X] Link to relevant issues in GitHub or Jira

### CODE REVIEW

File: src/main/java/com/adobe/jenkins/github_pr_comment_build/IssueCommentGHEventSubscriber.java [hunk 1]
```diff
@@ -161,13 +162,14 @@ public void run() {
                                                             changedRepository.getRepositoryName()
                                                     }
                                             );
+                                            break topLevel;
```
Comment (bluesliverx) [inline src/main/java/com/adobe/jenkins/github_pr_comment_build/IssueCommentGHEventSubscriber.java:165]: This can be simplified as a return statement.

Comment (bluesliverx) [inline src/main/java/com/adobe/jenkins/github_pr_comment_build/IssueCommentGHEventSubscriber.java:165]: This can be simplified as a return statement.

File: src/main/java/com/adobe/jenkins/github_pr_comment_build/PRReviewGHEventSubscriber.java [hunk 2]
```diff
@@ -118,7 +119,7 @@ public void run() {
                                         propFound = true;
                                         ParameterizedJobMixIn.scheduleBuild2(job, 0,
                                                 new CauseAction(new GitHubPullRequestReviewCause(pullRequestUrl)));
-                                        break;
+                                        break topLevel;
```
Comment (bluesliverx) [inline src/main/java/com/adobe/jenkins/github_pr_comment_build/PRReviewGHEventSubscriber.java:122]: Same here, this can be a return.

File: src/main/java/com/adobe/jenkins/github_pr_comment_build/PRUpdateGHEventSubscriber.java [hunk 3]
```diff
@@ -134,7 +135,7 @@ public void run() {
                                         propFound = true;
                                         ParameterizedJobMixIn.scheduleBuild2(job, 0,
                                                 new CauseAction(new GitHubPullRequestUpdateCause(pullRequestUrl)));
-                                        break;
+                                        break topLevel;
```
Comment (bluesliverx) [inline src/main/java/com/adobe/jenkins/github_pr_comment_build/PRUpdateGHEventSubscriber.java:138]: And same again.

**Comment by bluesliverx** [comment]
@lprimak, thanks for the contribution! Interesting that this is causing the problems, but I can see how possibly it could trigger a job twice if two SCM owners were attached to it and they both match. However, what happens here when there are legitimately multiple SCM sources that point at the same repository? In our Jenkins we have multiple jobs pointing at the same GitHub source repository. This changes plugin behavior in a way that would break the functionality for that use case I believe.

Can you provide more details on how this fixes the problem?

**Comment by lprimak** [comment]
There is only one SCM owner. The issue is intermittent.
I believe there is some kind of race condition in the event push logic in Jenkins causing two jobs to be selected in the loop.

I can see where a subtle cases could have the second job not being triggered.
However, I do believe that for 99% of the cases, this fix would work.

I do understand this change may not be acceptable. Do you have another suggestion?
Does `.equals()` on `Job<?,?>` work correctly? Would putting in a `Set<>` work to make the jobs unique?

**Comment by lprimak** [comment]
@bluesliverx what do you think of above? thanks!

**Comment by lprimak** [comment]
Thanks!

File: src/main/java/com/adobe/jenkins/github_pr_comment_build/IssueCommentGHEventSubscriber.java (hunk 1 above)
Comment (sparrowt) [inline src/main/java/com/adobe/jenkins/github_pr_comment_build/IssueCommentGHEventSubscriber.java:165]: Sadly this has broken the following workflow, in which we _expect_ multiple builds to be triggered:
- we have multiple jobs which each define `triggerPRCommentBranchProperty` e.g. one with `commentBody(".*foo this please.*")` and another with `commentBody(".*bar this please.*")`
- it was previously possible to comment on a PR like this and both jobs would be triggered:
```
foo this please
bar this please
```
- however now only 1 of them is triggered (whichever one the `for (Job...` loop gets to first)

The workaround is of course to do a separate comment for each one, but when you want to trigger 5 different custom test runs, this is a 5x increase in (a) effort to initiate, and (b) the amount of email spam sent to others watching the PR.

Perhaps if instead of doing `break` it instead checked whether `job` had already been scheduled, that would be a way of avoiding duplicates without stopping multiple different jobs being scheduled from the same comment?

Comment (bluesliverx) [reply src/main/java/com/adobe/jenkins/github_pr_comment_build/IssueCommentGHEventSubscriber.java:165]: We have been seeing issues for weeks with similar problems, and your comment just made me connect it to this PR. I'm downgrading the plugin on our Jenkins to verify that this is indeed the cause.

Comment (lprimak) [reply src/main/java/com/adobe/jenkins/github_pr_comment_build/IssueCommentGHEventSubscriber.java:165]: @sparrowt please open a new issue.
As I mentioned in the comment https://github.com/jenkinsci/github-pr-comment-build-plugin/pull/41#issuecomment-1095751180,
this would break the cases where multiple legitimate jobs would be triggered by a single comment.
Unfortunately I don't have the environment to test this on.
This PR fixes the 99% case where this plugin was broken for a long time, as reported in multiple issues by multiple people.

I can propose a short-term fix by adding a checkbox that turns off one-per-comment build  (default would be on) since that's 99% of the cases.

In the future if there is more interest to see what actually causes duplicate builds maybe there would be more time to take this on

**Comment by lprimak** [comment]
@bluesliverx please don't revert this. It breaks the 99% cases for this plugin.
I have time to put in a checkbox

**Comment by bluesliverx** [comment]
@lprimak sorry I've been out due to some personal things at home. I'm not planning on reverting this necessarily. I was saying that I downgraded the version that was installed on our Jenkins cluster to see if it helped, and it did indeed, so this is definitely the troublesome commit.

I like the solution proposed by someone else, look at the queue to see if it was already scheduled for the job to prevent multiple starts for a single job.

File: src/main/java/com/adobe/jenkins/github_pr_comment_build/IssueCommentGHEventSubscriber.java (hunk 1 above)
Comment (sparrowt) [reply src/main/java/com/adobe/jenkins/github_pr_comment_build/IssueCommentGHEventSubscriber.java:165]: Sorry I never got round to this - however it looks like https://github.com/jenkinsci/github-pr-comment-build-plugin/issues/49 was opened and https://github.com/jenkinsci/github-pr-comment-build-plugin/pull/48 fixes it (released in https://github.com/jenkinsci/github-pr-comment-build-plugin/releases/tag/82.v986d7874d9c5) so thank you!
